version: '3.1'

services:
  db:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - "./db/fiapfastfood.sql:/docker-entrypoint-initdb.d/fiapfastfood.sql"

  fastfood:
    container_name: fiap-fastfood
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - fastfood-network
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: fastfood
      DB_USERNAME: root
      DB_PASSWORD: rootpassword

networks:
  fastfood-network:
    driver: bridge
