version: '3.8'

services:
  fastfood:
    container_name: fiap-fastfood
    build:
      context: fastfood-api/.
      dockerfile: Dockerfile

  payment:
    container_name: fiap-payment
    build:
      context: payment-mock-api/.
      dockerfile: Dockerfile