version: '3.1'

services:
  mongo:
    image: docker.io/bitnami/mongodb:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - fastfood-network
    environment:
      MONGODB_USERNAME: common_user
      MONGODB_PASSWORD: password123
      MONGODB_DATABASE: fastfood
      MONGODB_ROOT_PASSWORD: rootpassword
    volumes:
      - 'mongodb_data:/fastfood'

  fastfood:
    container_name: fiap-fastfood
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - fastfood-network
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: fastfood
      DB_USERNAME: root
      DB_PASSWORD: rootpassword

networks:
  fastfood-network:
    driver: bridge
