version: '3.8'

services:
  fastfood:
    image: ghcr.io/icarodamiani/fastfood-api
    container_name: fiap-fastfood
    build:
      context: fastfood-api/.
      dockerfile: Dockerfile

  payment:
    image: ghcr.io/icarodamiani/payment-mock-api
    container_name: fiap-payment
    build:
      context: payment-mock-api/.
      dockerfile: Dockerfile