spring:
  application:
    name: fiap-fastfood

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  r2dbc:
    url: r2dbc:pool:mysql://${DB_HOST:localhost}:${DB_PORT}/${DB_DATABASE:fastfood}?zeroDateTimeBehavior=convertToNull&useSSL=false&useServerPrepareStatement=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpassword}