server:
  port: 8081
spring:
  application:
    name: fiap-payment

  cors:
    allowed-origins: "http://localhost:8080"
    allowed-headers: "Authorization, Content-Type, Accept"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,HEAD,TRACE,CONNECT,PATCH"
    max-age: 300

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    mongodb:
      repositories: true
      port: ${MONGODB_PORT:27018}
      auto-index-creation: true
      uuid-representation: standard
      host: ${MONGODB_HOST:localhost}
      authentication-database: admin
      database: ${MONGODB_DATABASE:payment}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:rootpassword}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:root}
    password: ${RABBITMQ_PASSWORD:rootpassword}
    template:
      retry:
        enabled: true
        initial-interval: 2s

management:
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"