spring:
  application:
    name: fiap-fastfood

  cors:
    allowed-origins: "http://localhost:8000"
    allowed-headers: "Authorization, Content-Type, Accept"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,HEAD,TRACE,CONNECT,PATCH"
    max-age: 300

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    mongodb:
      repositories: true
      port: ${MONGODB_PORT:27017}
      auto-index-creation: true
      uuid-representation: standard
      host: ${MONGODB_HOST:localhost}
      authentication-database: admin
      database: ${MONGODB_DATABASE:fastfood}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:rootpassword}

management:
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

payment:
  webhook: ${WEBHOOK_URL:http://localhost:8080/v1/payment/receive}
  client:
    connectionTimeout: 50000
    responseTimeout: 50000
    readTimeout: 50000
    writeTimeout: 50000
    maxConnections: 5
    url: ${PAYMENT_URL:http://localhost:8081}

