# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Docker-Compose GitHub Packages Publish
      uses: soltys/publish-docker-compose@v1.0.0
      with:
        # Release version (tag)
        version: 1.0.0-SNAPSHOT 
        docker_compose: docker-compose.yaml
    
    - name: Deploy Helm chart to AWS EKS Cluster
      # You may pin to the exact commit or the version.
      # uses: bitovi/github-actions-deploy-eks-helm@016d790e0f780d468a99a4ded0d10636d94daad5
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.9
      with:
        # AWS credentials used to login to eks.
        aws-secret-access-key: # optional
        # AWS credentials used to login to eks.
        aws-access-key-id: # optional
        # AWS region to use (default: us-west-2)
        aws-region: # default is us-west-2
        # EKS cluster name.
        cluster-name: 
        # EKS cluster admin role arn.
        cluster-role-arn: # optional
        # Comma separated list of helm values files.
        config-files: # optional
        # Kubernetes namespace to use.
        namespace: # optional
        # Comma separated list of value sets for helms. e.x: key1=value1,key2=value2
        values: # optional
        # Name of the helm deploy.
        name: 
        # Specify whether you want to install or uninstall the target helm chart
        action: # optional, default is install
        # Toggles dry-run flag for install/uninstall actions
        dry-run: # optional
        # The path of the chart.
        chart-path: # optional, default is helm/
        # The repository of the chart.
        chart-repository: # optional
        # The chart version
        version: # optional
        # Timeout for the job.
        timeout: # default is 0s
        # Update chart dependencies
        update-deps: # optional, default is true
        # Comma separated list of helm plugins to install. e.x: https://github.com/hypnoglow/helm-s3.git,https://github.com/someuser/helm-plugin.git
        plugins: # optional
        # Add the --wait flag to helm
        helm-wait: # optional
        # Add the --atomic flag to rollback on failure
        atomic: # optional
        # Verify certificates of HTTPS-enabled servers using this CA bundle.
        ca-file: # optional
        # Identify HTTPS client using this SSL certificate file.
        cert-file: # optional
        # Identify HTTPS client using this SSL key file.
        key-file: # optional
        # Skip tls certificate checks for the chart download.
        insecure-skip-tls-verify: # optional
        # Pass credentials to all domains.
        pass-credentials: # optional
        # Chart repository password where to locate the requested chart.
        password: # optional
        # Chart repository username where to locate the requested chart.
        username: # optional
        # Uses the secrets with vals backend to apply the chart
        use-secrets-vals: # optional
        # Append any string containing any extra option that might escape the ones present in this action.
        helm-extra-args: # optional
